name: CI

on:
  pull_request:
  push:
    branches: [ main, develop, feature/** ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: app_test
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd="pg_isready -U app -d app_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: app
      DB_PASSWORD: app
      DB_NAME: app_test
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Корневые dev-зависимости: cypress, wait-on, http-server
      - name: Install root dev deps (npm)
        run: npm ci || npm i

      - name: Enable Corepack + pin Yarn 4.9.4
        run: |
          corepack enable
          corepack prepare yarn@4.9.4 --activate
          yarn -v

      - name: Install backend deps (yarn)
        working-directory: yourstyle-backend
        run: |
          yarn install --immutable || yarn install

      - name: Wait for Postgres to be ready
        env:
          PGPASSWORD: app
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U app -d app_test && exit 0
            echo "Postgres not ready yet, retry $i/30"; sleep 2
          done
          echo "Postgres did not become ready in time"; exit 1

      - name: DB migrate + seed
        working-directory: yourstyle-backend
        run: |
          yarn migrate
          yarn seed

      - name: Start backend (3001)
        working-directory: yourstyle-backend
        env:
          PORT: 3001
        run: nohup yarn start > ../backend.log 2>&1 &

      - name: Show first lines of backend log
        run: |
          [[ -f backend.log ]] && head -n 100 backend.log || true

      - name: Wait for backend (timeout 120s)
        run: |
          set -e
          if npx wait-on --timeout 120000 http://localhost:3001/healthz; then
            echo "Backend is up"
          else
            echo "Backend did not start in time"
            echo "----- backend.log -----"
            [[ -f backend.log ]] && tail -n +1 backend.log || echo "backend.log not found"
            echo "----- listening ports -----"
            ss -lntp || true
            exit 1
          fi

      # Фронтенд — статика из папки hitech-shop
      - name: Start static frontend (3000)
        run: nohup npx http-server ./hitech-shop -p 3000 -a 127.0.0.1 > frontend.log 2>&1 &

      - name: Wait for frontend (timeout 60s)
        run: |
          set -e
          if npx wait-on --timeout 60000 http://localhost:3000; then
            echo "Frontend is up"
          else
            echo "Frontend did not start in time"
            echo "----- frontend.log -----"
            [[ -f frontend.log ]] && tail -n +1 frontend.log || echo "frontend.log not found"
            ss -lntp || true
            exit 1
          fi

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          headless: true
          browser: chrome
          spec: cypress/e2e/**/*.cy.{js,ts}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
            backend.log
            frontend.log